/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ILegendData } from "./components/aon-legend/aon-legend";
import { ILegendData as ILegendData1 } from "./components/aon-legend/aon-legend";
import { IGridData } from "./components/aon-lol-grid/aon-lol-grid";
import { IStatusCardData } from "./components/aon-status-card/aon-status-card";
export namespace Components {
    interface AonLegend {
        "data": ILegendData[];
    }
    interface AonLegendItem {
        "color": string;
        "text": string;
    }
    interface AonLolGrid {
        "data": IGridData[];
        "legendData": ILegendData1[];
    }
    interface AonStatusCard {
        "data": IStatusCardData;
    }
}
declare global {
    interface HTMLAonLegendElement extends Components.AonLegend, HTMLStencilElement {
    }
    var HTMLAonLegendElement: {
        prototype: HTMLAonLegendElement;
        new (): HTMLAonLegendElement;
    };
    interface HTMLAonLegendItemElement extends Components.AonLegendItem, HTMLStencilElement {
    }
    var HTMLAonLegendItemElement: {
        prototype: HTMLAonLegendItemElement;
        new (): HTMLAonLegendItemElement;
    };
    interface HTMLAonLolGridElement extends Components.AonLolGrid, HTMLStencilElement {
    }
    var HTMLAonLolGridElement: {
        prototype: HTMLAonLolGridElement;
        new (): HTMLAonLolGridElement;
    };
    interface HTMLAonStatusCardElement extends Components.AonStatusCard, HTMLStencilElement {
    }
    var HTMLAonStatusCardElement: {
        prototype: HTMLAonStatusCardElement;
        new (): HTMLAonStatusCardElement;
    };
    interface HTMLElementTagNameMap {
        "aon-legend": HTMLAonLegendElement;
        "aon-legend-item": HTMLAonLegendItemElement;
        "aon-lol-grid": HTMLAonLolGridElement;
        "aon-status-card": HTMLAonStatusCardElement;
    }
}
declare namespace LocalJSX {
    interface AonLegend {
        "data": ILegendData[];
    }
    interface AonLegendItem {
        "color"?: string;
        "text"?: string;
    }
    interface AonLolGrid {
        "data": IGridData[];
        "legendData": ILegendData1[];
    }
    interface AonStatusCard {
        "data": IStatusCardData;
    }
    interface IntrinsicElements {
        "aon-legend": AonLegend;
        "aon-legend-item": AonLegendItem;
        "aon-lol-grid": AonLolGrid;
        "aon-status-card": AonStatusCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aon-legend": LocalJSX.AonLegend & JSXBase.HTMLAttributes<HTMLAonLegendElement>;
            "aon-legend-item": LocalJSX.AonLegendItem & JSXBase.HTMLAttributes<HTMLAonLegendItemElement>;
            "aon-lol-grid": LocalJSX.AonLolGrid & JSXBase.HTMLAttributes<HTMLAonLolGridElement>;
            "aon-status-card": LocalJSX.AonStatusCard & JSXBase.HTMLAttributes<HTMLAonStatusCardElement>;
        }
    }
}
